version: '3.8'

services:
  reviewer:
#    build: .
    image: ghcr.io/hayridurmaz/tfs-ai-code-reviewer:latest
    container_name: ai-pr-reviewer
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data
    # Command is handled by Dockerfile (./reviewer)
